<template>
    <option v-for="option in DocTypeOptions" :key="option.value" :value="option.value">
        {{ option.text }}
    </option>
</template>

<script>
    export default {
        props: {},
        data() {
            return {
                DocTypeOptions: [
					{ text:'Accomplishment Report', value: 'Accomplishment Report' },
					{ text:'Accomplishment Receipt Equipment', value: 'Accomplishment Receipt Equipment' },
					{ text:'Acknowledgement Receipt', value: 'Acknowledgement Receipt' },
					{ text:'Activity Design', value: 'Activity Design' },
					{ text:'Administrative Order', value: 'Administrative Order' },
					{ text:'Advertising Invoice', value: 'Advertising Invoice' },
					{ text:'Advertising Quotation', value: 'Advertising Quotation' },
					{ text:'Advisory', value: 'Advisory' },
					{ text:'Affidavit of Non-Disclosure', value: 'Affidavit of Non-Disclosure' },
					{ text:'Agency Procurement Request', value: 'Agency Procurement Request' },
					{ text:'Annual Procurement Plan', value: 'Annual Procurement Plan' },
					{ text:'Application', value: 'Application' },
					{ text:'Application for Permit to Construct - Birthing Home', value: 'Application for Permit to Construct - Birthing Home' },
					{ text:'Application for Accreditation - Drug Abuse Treatment & Rehab Center', value: 'Application for Accreditation - Drug Abuse Treatment & Rehab Center' },
					{ text:'Application for Accreditation - Drug Testing Laboratory', value: 'Application for Accreditation - Drug Testing Laboratory' },
					{ text:'Application for Accreditation - Medical Facility for OW & Seafarers', value: 'Application for Accreditation - Medical Facility for OW & Seafarers' },
					{ text:'Application for Accreditation - Stem Cell', value: 'Application for Accreditation - Stem Cell' },
					{ text:'Application for Clearance to Operate - HMO', value: 'Application for Clearance to Operate - HMO' },
					{ text:'Application for LTO - Ambulatory Surgical Clinic', value: 'Application for LTO - Ambulatory Surgical Clinic' },
					{ text:'Application for LTO - Birthing Homes', value: 'Application for LTO - Birthing Homes' },
					{ text:'Application for LTO - Dialysis Clinic', value: 'Application for LTO - Dialysis Clinic' },
					{ text:'Application for LTO - Hospital', value: 'Application for LTO - Hospital' },
					{ text:'Application for LTO - Infirmary', value: 'Application for LTO - Infirmary' },
					{ text:'Application for LTO - Kidney Transplant', value: 'Application for LTO - Kidney Transplant' },
					{ text:'Application for Permit to Construct - Blood Testing', value: 'Application for Permit to Construct - Blood Testing' },
					{ text:'Application for Permit to Construct - Dialysis Clinic', value: 'Application for Permit to Construct - Dialysis Clinic' },
					{ text:'Application for Permit to Construct - Drug Testing Laboratory', value: 'Application for Permit to Construct - Drug Testing Laboratory' },
					{ text:'Application for Permit to Construct - Hospital', value: 'Application for Permit to Construct - Hospital' },
					{ text:'Application for Permit to Construct - Infirmary', value: 'Application for Permit to Construct - Infirmary' },
					{ text:'Application for Permit to Construct - Medical Faciltiy for OW & Seafarers', value: 'Application for Permit to Construct - Medical Faciltiy for OW & Seafarers' },
					{ text:'Application for Permti to Construct - Ambulatory Surgical Clinic', value: 'Application for Permti to Construct - Ambulatory Surgical Clinic' },
					{ text:'Appln. for LTO/Accreditation', value: 'Appln. for LTO/Accreditation' },
					{ text:'Appointment Paper', value: 'Appointment Paper' },
					{ text:'Assets/Liabilities', value: 'Assets/Liabilities' },
					{ text:'Authority to Operate Blood Testing', value: 'Authority to Operate Blood Testing' },
					{ text:'Bidding Documents', value: 'Bidding Documents' },
					{ text:'Budget Utilization Request', value: 'Budget Utilization Request' },
					{ text:'C.T.O. Application', value: 'C.T.O. Application' },
					{ text:'CAF', value: 'CAF' },
					{ text:'Canvass', value: 'Canvass' },
					{ text:'Cert of No Pending Admini Case', value: 'Cert of No Pending Admini Case' },
					{ text:'Certificate - SSRS', value: 'Certificate - SSRS' },
					{ text:'Certificate of Employment', value: 'Certificate of Employment' },
					{ text:'Certificate of Registration', value: 'Certificate of Registration' },
					{ text:'Certificate of Undertaking', value: 'Certificate of Undertaking' },
					{ text:'Certificate Project Acceptance', value: 'Certificate Project Acceptance' },
					{ text:'Certificate System Acceptance', value: 'Certificate System Acceptance' },
					{ text:'Certificate Training/Diploma', value: 'Certificate Training/Diploma' },
					{ text:'Certificates', value: 'Certificates' },
					{ text:'Certification - TWG Honorarium', value: 'Certification - TWG Honorarium' },
					{ text:'Certification for Reimbursement', value: 'Certification for Reimbursement' },
					{ text:'Charge Account Order Slip', value: 'Charge Account Order Slip' },
					{ text:'CHT Reports', value: 'CHT' },
					{ text:'Clearance', value: 'Clearance' },
					{ text:'Clearance - PNDF Exemption', value: 'Clearance - PNDF Exemption' },
					{ text:'Clearance Certificate', value: 'Clearance Certificate' },
					{ text:'Clearing House of Purchase Req', value: 'Clearing House of Purchase Req' },
					{ text:'COBAC Resolution', value: 'COBAC Resolution' },
					{ text:'Complaints', value: 'Complaints' },
					{ text:'Compliance', value: 'Compliance' },
					{ text:'Compliance Requirements', value: 'Compliance Requirements' },
					{ text:'Confirmatory Result', value: 'Confirmatory Result' },
					{ text:'Contract', value: 'Contract' },
					{ text:'Contract - Advertisement', value: 'Contract - Advertisement' },
					{ text:'Contract of Service', value: 'Contract of Service' },
					{ text:'Credit Slip Form', value: 'Credit Slip Form' },
					{ text:'Daily Monitoring & Endorsement', value: 'Daily Monitoring & Endorsement' },
					{ text:'Delivery Receipt', value: 'Delivery Receipt' },
					{ text:'Department Circular', value: 'Department Circular' },
					{ text:'Department Memorandum', value: 'Department Memorandum' },
					{ text:'Department Order', value: 'Department Order' },
					{ text:'Department Personnel Order', value: 'Department Personnel Order' },
					{ text:'Disbursement Voucher', value: 'Disbursement Voucher' },
					{ text:'DTR', value: 'DTR' },
					{ text:'EDPMS Report', value: 'EDPMS Report' },
					{ text:'Endorsement', value: 'Endorsement' },
					{ text:'Executive Order', value: 'Executive Order' },
					{ text:'Flash Report', value: 'Flash Report' },
					{ text:'Fuel Request Form', value: 'Fuel Request Form' },
					{ text:'Fund Transfer', value: 'Fund Transfer' },
					{ text:'FYI (For your information)', value: 'FYI (For your information)' },
					{ text:'Gate / Building Pass', value: 'Gate / Building Pass' },
					{ text:'HEARS', value: 'HEARS' },
					{ text:'HEARS Update', value: 'HEARS Update' },
					{ text:'Incidental Report', value: 'Incidental Report' },
					{ text:'Inspection & Acceptance Report', value: 'Inspection & Acceptance Report' },
					{ text:'Inspection Report', value: 'Inspection Report' },
					{ text:'Inventory & Inspection Report', value: 'Inventory & Inspection Report' },
					{ text:'Inventory Checklist', value: 'Inventory Checklist' },
					{ text:'Inventory Report', value: 'Inventory Report' },
					{ text:'Invitation', value: 'Invitation' },
					{ text:'Invoice Receipt - Equipment', value: 'Invoice Receipt - Equipment' },
					{ text:'Invoice Receipt of Property', value: 'Invoice Receipt of Property' },
					{ text:'IPCR', value: 'IPCR' },
					{ text:'Job Hiring (Announcement)', value: 'Job Hiring (Announcement)' },
					{ text:'Job Order', value: 'Job Order' },
					{ text:'Leave Application', value: 'Leave Application' },
					{ text:'Legal Decision', value: 'Legal Decision' },
					{ text:'Legislative Advisory', value: 'Legislative Advisory' },
					{ text:'Letter', value: 'Letter' },
					{ text:'Letter - Complaint', value: 'Letter - Complaint' },
					{ text:'Letter - Endorsement', value: 'Letter - Endorsement' },
					{ text:'Letter - For Information', value: 'Letter - For Information' },
					{ text:'Letter - Inquiry', value: 'Letter - Inquiry' },
					{ text:'Letter - Invitation', value: 'Letter - Invitation' },
					{ text:'Letter - Referral', value: 'Letter - Referral' },
					{ text:'Letter - Request', value: 'Letter - Request' },
					{ text:'Letter for Inclusion', value: 'Letter for Inclusion' },
					{ text:'License to Operate', value: 'License to Operate' },
					{ text:'Liquidation Report', value: 'Liquidation Report' },
					{ text:'Logistic Request Form', value: 'Logistic Request Form' },
					{ text:'Mail', value: 'Mail' },
					{ text:'Mailing Envelope for Mail', value: 'Mailing Envelope for Mail' },
					{ text:'Manual', value: 'Manual' },
					{ text:'Meal Provision Request Form', value: 'Meal Provision Request Form' },
					{ text:'Memo of Understanding (MOU)', value: 'Memo of Understanding (MOU)' },
					{ text:'Memorandum', value: 'Memorandum' },
					{ text:'Memorandum Circular', value: 'Memorandum Circular' },
					{ text:'Memorandum of Agreement (MOA)', value: 'Memorandum of Agreement (MOA)' },
					{ text:'Memorandum of Understanding', value: 'Memorandum of Understanding' },
					{ text:'Memorandum Receipt', value: 'Memorandum Receipt' },
					{ text:'Monthly Report of Attendance', value: 'Monthly Report of Attendance' },
					{ text:'Monthly Statistical Report', value: 'Monthly Statistical Report' },
					{ text:'MSW Annual Narrative Report', value: 'MSW Annual Narrative Report' },
					{ text:'MSW Annual Psychosocial Report', value: 'MSW Annual Psychosocial Report' },
					{ text:'MSW Annual Statistical Report', value: 'MSW Annual Statistical Report' },
					{ text:'News Clippings', value: 'News Clippings' },
					{ text:'Notice of Award', value: 'Notice of Award' },
					{ text:'Notice of Meeting', value: 'Notice of Meeting' },
					{ text:'Obligation Request', value: 'Obligation Request' },
					{ text:'Office Memorandum', value: 'Office Memorandum' },
					{ text:'Office Order', value: 'Office Order' },
					{ text:'OPCR', value: 'OPCR' },
					{ text:'Other Documents', value: 'Other Documents' },
					{ text:'Payroll', value: 'Payroll' },
					{ text:'Permit to construct', value: 'Permit to construct' },
					{ text:'PES', value: 'PES' },
					{ text:'Petty Cash Voucher', value: 'Petty Cash Voucher' },
					{ text:'PLDT', value: 'PLDT' },
					{ text:'PO PROCESSING', value: 'PO PROCESSING' },
					{ text:'Position Paper', value: 'Position Paper' },
					{ text:'Post Mission Report', value: 'Post Mission Report' },
					{ text:'Post Travel Report', value: 'Post Travel Report' },
					{ text:'PPMP', value: 'PPMP' },
					{ text:'PR with CANVASS', value: 'PR with CANVASS' },
					{ text:'Pre-Repair Inspection', value: 'Pre-Repair Inspection' },
					{ text:'Pre/Post Repair Inspection Rep', value: 'Pre/Post Repair Inspection Rep' },
					{ text:'Price Report', value: 'Price Report' },
					{ text:'Proposal', value: 'Proposal' },
					{ text:'Provision Request Form', value: 'Provision Request Form' },
					{ text:'Purchase Order', value: 'Purchase Order' },
					{ text:'Purchase Request', value: 'Purchase Request' },
					{ text:'Radio Base Checklist', value: 'Radio Base Checklist' },
					{ text:'Regional Personnel Order', value: 'Regional Personnel Order' },
					{ text:'Reimbursement', value: 'Reimbursement' },
					{ text:'Remote Collection Permit', value: 'Remote Collection Permit' },
					{ text:'Renewal/Initial', value: 'Renewal/Initial' },
					{ text:'Replenishment', value: 'Replenishment' },
					{ text:'Replenishment of Mailing', value: 'Replenishment of Mailing' },
					{ text:'Reports', value: 'Reports' },
					{ text:'Request and Issue Slip', value: 'Request and Issue Slip' },
					{ text:'Request Financial Assistance', value: 'Request Financial Assistance' },
					{ text:'Request for Action', value: 'Request for Action' },
					{ text:'Request for Action Slip - QMS', value: 'Request for Action Slip - QMS' },
					{ text:'Request for Quotation', value: 'Request for Quotation' },
					{ text:'Request for Tagging', value: 'Request for Tagging' },
					{ text:'Resolutions', value: 'Resolutions' },
					{ text:'Sales Invoice', value: 'Sales Invoice' },
					{ text:'Service Level Agreement', value: 'Service Level Agreement' },
					{ text:'Service Order', value: 'Service Order' },
					{ text:'Service Record', value: 'Service Record' },
					{ text:'Service Request', value: 'Service Request' },
					{ text:'Statement of Account', value: 'Statement of Account' },
					{ text:'Supplemental APP', value: 'Supplemental APP' },
					{ text:'Supplies Availability Inquiry', value: 'Supplies Availability Inquiry' },
					{ text:'TACT Clearance', value: 'TACT Clearance' },
					{ text:'TACT FORM', value: 'TACT FORM' },
					{ text:'Terms of Reference', value: 'Terms of Reference' },
					{ text:'Travel Authority', value: 'Travel Authority' },
					{ text:'Travel Liquidation', value: 'Travel Liquidation' },
					{ text:'Travel Reimbursement', value: 'Travel Reimbursement' },
					{ text:'Utilization Report', value: 'Utilization Report' },
					{ text:'Vehicle Request', value: 'Vehicle Request' },
					{ text:'Vehicle Request Form', value: 'Vehicle Request Form' },
					{ text:'VOUCHERS', value: 'VOUCHERS' },
					{ text:'Waste Material Report', value: 'Waste Material Report' },
					{ text:'WFP', value: 'WFP' },
				],
            }
        },
        created(){
        },
        methods:{

        }
    }
</script>